<a href="https://colab.research.google.com/github/imprakhartripathi/GoogleColabCodesForML/blob/main/ml_lab_four.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data PreProcessing

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/datapreprocessing.csv')

data

country   age  salary purchased
0    india  28.0  7200.0       yes
1   france   NaN  8500.0        no
2    itlay  60.0  1200.0       yes
3    spain  55.0  4600.0        no
4  germany  86.0     NaN       yes

In [ ]:
y = data[['purchased']]
y

purchased
0       yes
1        no
2       yes
3        no
4       yes

In [ ]:
x = data[['country', 'age', 'salary']]
x

country   age  salary
0    india  28.0  7200.0
1   france   NaN  8500.0
2    itlay  60.0  1200.0
3    spain  55.0  4600.0
4  germany  86.0     NaN

In [ ]:
x = data[['country', 'age', 'salary']].values
x

array([['india', 28.0, 7200.0],
       ['france', nan, 8500.0],
       ['itlay', 60.0, 1200.0],
       ['spain', 55.0, 4600.0],
       ['germany', 86.0, nan]], dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
x

array([['india', 28.0, 7200.0],
       ['france', 57.25, 8500.0],
       ['itlay', 60.0, 1200.0],
       ['spain', 55.0, 4600.0],
       ['germany', 86.0, 5375.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
x[:, 0] = label_encoder_x.fit_transform(x[:, 0])
x

array([[2, 28.0, 7200.0],
       [0, 57.25, 8500.0],
       [3, 60.0, 1200.0],
       [4, 55.0, 4600.0],
       [1, 86.0, 5375.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder
onehotendoder = OneHotEncoder()
x = onehotendoder.fit_transform(data.country.values.reshape(-1,1)).toarray()
x

array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.]])

In [ ]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 1, 0, 1])