<a href="https://colab.research.google.com/github/imprakhartripathi/GoogleColabCodesForML/blob/main/ml_lab_four.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data PreProcessing

In [13]:
import pandas as pd
import numpy as np

In [14]:
data = pd.read_csv('/content/Data_for_preprocessing.csv')

data

country   age   salary purchased
0    india  28.0  72000.0       yes
1   france   NaN  55000.0        no
2    italy  60.0  45000.0        no
3    spain  55.0      NaN       yes
4  germany  45.0  78000.0       yes

In [15]:
y = data[['purchased']]
y

purchased
0       yes
1        no
2        no
3       yes
4       yes

In [16]:
x = data[['country', 'age', 'salary']]
x

country   age   salary
0    india  28.0  72000.0
1   france   NaN  55000.0
2    italy  60.0  45000.0
3    spain  55.0      NaN
4  germany  45.0  78000.0

In [17]:
x = data[['country', 'age', 'salary']].values
x

array([['india', 28.0, 72000.0],
       ['france', nan, 55000.0],
       ['italy', 60.0, 45000.0],
       ['spain', 55.0, nan],
       ['germany', 45.0, 78000.0]], dtype=object)

In [18]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
x

array([['india', 28.0, 72000.0],
       ['france', 47.0, 55000.0],
       ['italy', 60.0, 45000.0],
       ['spain', 55.0, 62500.0],
       ['germany', 45.0, 78000.0]], dtype=object)

In [19]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x = LabelEncoder()
x[:, 0] = label_encoder_x.fit_transform(x[:, 0])
x

array([[2, 28.0, 72000.0],
       [0, 47.0, 55000.0],
       [3, 60.0, 45000.0],
       [4, 55.0, 62500.0],
       [1, 45.0, 78000.0]], dtype=object)

In [20]:
from sklearn.preprocessing import OneHotEncoder
onehotendoder = OneHotEncoder(sparse_output=False, dtype=int)
x = onehotendoder.fit_transform(data.country.values.reshape(-1,1))
x

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0]])

In [21]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
y

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([1, 0, 0, 1, 1])